version: 2

sources:
  - name: dbt_bq_example
    database: "{{ env_var('PROJECT_ID', 'dbt-demo-386220') }}" 
    schema: dbt_bq_example

    freshness:
      warn_after: { count: 10, period: day } # 1 day old from time you run the source snapshot command
      error_after: { count: 1095, period: day } # 2 days old from time you run the source snapshot command

    loaded_at_field: order_date

    tables:
      - name: raw_customers
        freshness: null # no freshness tests
      - name: raw_orders
      - name: raw_payments
        freshness: null # no freshness tests
